name: release

on:
  push:
    tags:
      - '**'

jobs:
  releases-matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ linux, windows, darwin ]
        arch: [ amd64, arm64 ]
    permissions:
      contents: write

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install Node dependencies
        run: yarn install

      - name: Make
        run: npm run make

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-${{ matrix.arch }}-artifacts
          path: |
            out/make/deb/**/*.deb
            out/make/rpm/**/*.rpm
            out/make/squirrel.windows/**/*.exe
            out/make/zip/**/**/*.zip
            out/make/zip/darwin/**/*.zip
            out/make/*.dmg

  create-release:
    needs: [releases-matrix]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4

      - name: Display structure of downloaded files
        run: ls -R

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          generateReleaseNotes: true
          artifacts: |
            **/**/*.deb
            **/**/*.rpm
            **/**/*.exe
            **/**/*.zip
            **/**/*.dmg
