name: release

on:
  push:
    tags:
      - '**'

jobs:
  releases-matrix:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    permissions:
      contents: write

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      # try earlier python version for appdmg
      # https://github.com/electron/forge/issues/3371#issuecomment-2105195302
      - name: Install Python 3.11.4
        if: startsWith(matrix.os, 'macos-')
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.4'

      - name: Install Node dependencies
        run: npm ci

      - name: setup windows certificate
        if: startsWith(matrix.os, 'windows-')
        run: |
          $bytes = [Convert]::FromBase64String("${{ secrets.WINDOWS_CERTIFICATE }}")
          [IO.File]::WriteAllBytes("certificate.pfx", $bytes)
        env:
          WINDOWS_CERTIFICATE: ${{ secrets.WINDOWS_CERTIFICATE }}

      - name: publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WINDOWS_CERTIFICATE_PATH: ./certificate.pfx
          WINDOWS_CERTIFICATE_PASSWORD: ${{ secrets.WINDOWS_CERTIFICATE_PASSWORD }}
        run: npm run publish

